[package]
name = "vshark"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
pcap-parser = "0.16"
etherparse = "0.14"
nucleo = "0.2"
